antora:
  extensions:
    # Patch old metadata to ensure that only latest is displayed
    - ./lib/antora/extensions/fix-component-name-display.js
    - ./lib/antora/extensions/version-fix.js
    - require: '@springio/antora-extensions'
      root_component_name: 'session'
site:
  title: Spring Session
  url: https://docs.spring.io/spring-session/reference
  robots: allow
git:
  ensure_git_suffix: false
content:
  sources:
  - url: https://github.com/spring-projects/spring-session
    branches: [main, '+({0..9}).+({0..9}).x', '!(1.*.x)', '!(2.*.x)','!(3.{0..2}.x)']
    tags: ['2.{6..9}.*', '3.+({0..9}).+({0..9})?(-{RC,M}*)?', '!2.6.0-M*','!2.6.0-RC*','!2.7.0-M1','!3.0.0-M1']
    start_path: spring-session-docs
asciidoc:
  attributes:
    page-stackoverflow-url: https://stackoverflow.com/tags/spring-session
    page-related-doc-categories: security
    page-related-doc-projects: framework
    page-pagination: ''
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
  extensions:
    - '@asciidoctor/tabs'
    - '@springio/asciidoctor-extensions'
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.4.18/ui-bundle.zip
    snapshot: true
runtime:
  log:
    level: info
