antora:
  extensions:
    - '@springio/antora-extensions/partial-build-extension'
    - require: '@springio/antora-extensions/latest-version-extension'
    - ./lib/antora/extensions/inject-collector-config.js
    - '@antora/collector-extension'
    - ./lib/antora/extensions/version-fix.js
    - '@antora/atlas-extension'
    - '@opendevise/antora-release-line-extension'
    - require: '@springio/antora-extensions/tabs-migration-extension'
      # uncomment this option to save the migrated content to the worktree
      #save_result: true
      unwrap_example_block: always
    - require: ./lib/antora/extensions/publish-docsearch-config
      template_path: ./.github/actions/docsearch-config.json.hbs
    - require: '@springio/antora-extensions/root-component-extension'
      root_component_name: 'session'
site:
  title: Spring Session
  url: https://docs.spring.io/spring-session/reference
  robots: allow
git:
  ensure_git_suffix: false
content:
  sources:
  - url: https://github.com/spring-projects/spring-session
    branches: [main, '*.x', '!(1.*.x)', '!(2.{0..5}.x)']
    tags: ['2.{6..9}.*', '3.+({0..9}).+({0..9})?(-{RC,M}*)?', '!2.6.0-M*','!2.6.0-RC*','!2.7.0-M1','!3.0.0-M1']
    start_path: spring-session-docs
asciidoc:
  attributes:
    page-pagination: ''
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
  extensions:
    - '@asciidoctor/tabs'
    - '@springio/asciidoctor-extensions'
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.3.0/ui-bundle.zip
    snapshot: true
