[versions]
ch-qos-logback = "1.4.14"
jakarta-websocket = "2.1.1"
org-apache-derby = "10.16.1.1"
org-codehaus-groovy = "3.0.19"
org-gretty = "4.1.1"
org-mockito = "5.5.0"
org-mongodb = "4.11.2"
org-seleniumhq-selenium = "4.8.3"
org-slf4j = "2.0.12"
org-testcontainers = "1.18.3"
org-springframework-boot = "3.2.4"

[libraries]
ch-qos-logback-logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "ch-qos-logback" }
ch-qos-logback-logback-core = { module = "ch.qos.logback:logback-core", version.ref = "ch-qos-logback" }
com-fasterxml-jackson-jackson-bom = "com.fasterxml.jackson:jackson-bom:2.15.4"
com-fasterxml-jackson-core-jackson-databind = "com.fasterxml.jackson.core:jackson-databind:2.15.4"
com-google-code-findbugs-jsr305 = "com.google.code.findbugs:jsr305:3.0.2"
com-h2database-h2 = "com.h2database:h2:2.2.224"
com-hazelcast = "com.hazelcast:hazelcast:5.3.7"
com-ibm-db2-jcc = "com.ibm.db2:jcc:11.5.9.0"
com-maxmind-geoip2 = "com.maxmind.geoip2:geoip2:2.16.1"
com-microsoft-sqlserver-mssql-jdbc = "com.microsoft.sqlserver:mssql-jdbc:11.2.3.jre17"
com-oracle-database-jdbc-ojdbc8 = "com.oracle.database.jdbc:ojdbc8:21.10.0.0"
com-zaxxer-HikariCP = "com.zaxxer:HikariCP:5.0.1"
edu-umd-cs-mtc-multithreadedtc = "edu.umd.cs.mtc:multithreadedtc:1.01"
io-lettuce-lettuce-core = "io.lettuce:lettuce-core:6.2.7.RELEASE"
io-projectreactor-reactor-bom = "io.projectreactor:reactor-bom:2023.0.5"
io-spring-javaformat-spring-javaformat-checkstyle = "io.spring.javaformat:spring-javaformat-checkstyle:0.0.41"
io-spring-nohttp-nohttp-checkstyle = "io.spring.nohttp:nohttp-checkstyle:0.0.11"
jakarta-servlet-jakarta-servlet-api = "jakarta.servlet:jakarta.servlet-api:6.0.0"
jakarta-servlet-jsp-jstl-jakarta-servlet-jsp-jstl-api = "jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api:3.0.0"
jakarta-websocket-jakarta-websocket-api = { module = "jakarta.websocket:jakarta.websocket-api", version.ref = "jakarta-websocket" }
jakarta-websocket-jakarta-websocket-client-api = { module = "jakarta.websocket:jakarta.websocket-client-api", version.ref = "jakarta-websocket" }
mysql-mysql-connector-java = "mysql:mysql-connector-java:8.0.33"
nz-net-ultraq-thymeleaf-thymeleaf-layout-dialect = "nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect:3.2.1"
com-squareup-okhttp3-okhttp = "com.squareup.okhttp3:okhttp:3.14.9"
org-apache-derby-derby = { module = "org.apache.derby:derby", version.ref = "org-apache-derby" }
org-apache-derby-derbytools = { module = "org.apache.derby:derbytools", version.ref = "org-apache-derby" }
org-apache-httpcomponents-httpclient = "org.apache.httpcomponents:httpclient:4.5.14"
org-apache-logging-log4j-log4j-core = "org.apache.logging.log4j:log4j-core:2.17.2"
org-aspectj-aspectjweaver = "org.aspectj:aspectjweaver:1.9.22"
org-assertj-assertj-core = "org.assertj:assertj-core:3.24.2"
org-hamcrest = "org.hamcrest:hamcrest:2.2"
org-hsqldb = "org.hsqldb:hsqldb:2.7.2"
org-junit-junit-bom = "org.junit:junit-bom:5.8.2"
org-mariadb-jdbc-mariadb-java-client = "org.mariadb.jdbc:mariadb-java-client:3.1.4"
org-mockito-mockito-bom = { module = "org.mockito:mockito-bom", version.ref = "org-mockito" }
org-mongodb-mongodb-driver-core = { module = "org.mongodb:mongodb-driver-core", version.ref = "org-mongodb" }
org-mongodb-mongodb-driver-reactivestreams = { module = "org.mongodb:mongodb-driver-reactivestreams", version.ref = "org-mongodb" }
org-mongodb-mongodb-driver-sync = { module = "org.mongodb:mongodb-driver-sync", version.ref = "org-mongodb" }
org-postgresql = "org.postgresql:postgresql:42.6.2"
org-seleniumhq-selenium-htmlunit-driver = { module = "org.seleniumhq.selenium:htmlunit-driver", version.ref = "org-seleniumhq-selenium" }
org-seleniumhq-selenium-selenium-support = { module = "org.seleniumhq.selenium:selenium-support", version.ref = "org-seleniumhq-selenium" }
org-skyscreamer-jsonassert = "org.skyscreamer:jsonassert:1.5.1"
org-slf4j-jcl-over-slf4j = { module = "org.slf4j:jcl-over-slf4j", version.ref = "org-slf4j" }
org-slf4j-log4j-over-slf4j = { module = "org.slf4j:log4j-over-slf4j", version.ref = "org-slf4j" }
org-slf4j-slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "org-slf4j" }
org-springframework-data-spring-data-bom = "org.springframework.data:spring-data-bom:2023.1.4"
org-springframework-security-spring-security-bom = "org.springframework.security:spring-security-bom:6.2.3"
org-springframework-spring-framework-bom = "org.springframework:spring-framework-bom:6.1.6"
org-springframework-boot-spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "org-springframework-boot" }
org-springframework-boot-spring-boot-gradle-plugin = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "org-springframework-boot" }
org-testcontainers-testcontainers-bom = { module = "org.testcontainers:testcontainers-bom", version.ref = "org-testcontainers" }
io-spring-security-release-plugin = "io.spring.gradle:spring-security-release-plugin:1.0.2"

[plugins]
