[versions]
ch-qos-logback = "1.4.11"
io-projectreactor = "3.4.34"
jakarta-websocket = "2.1.1"
org-apache-derby = "10.16.1.1"
org-codehaus-groovy = "3.0.19"
org-gretty = "4.1.1"
org-mongodb = "4.8.2"
org-slf4j = "2.0.9"
org-springframework-boot = "3.0.12"
org-testcontainers = "1.17.6"

[libraries]
ch-qos-logback-logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "ch-qos-logback" }
ch-qos-logback-logback-core = { module = "ch.qos.logback:logback-core", version.ref = "ch-qos-logback" }
com-fasterxml-jackson-jackson-bom = "com.fasterxml.jackson:jackson-bom:2.14.3"
com-fasterxml-jackson-core-jackson-databind = "com.fasterxml.jackson.core:jackson-databind:2.14.3"
com-google-code-findbugs-jsr305 = "com.google.code.findbugs:jsr305:3.0.2"
com-h2database-h2 = "com.h2database:h2:2.1.214"
com-hazelcast = "com.hazelcast:hazelcast:5.1.7"
com-ibm-db2-jcc = "com.ibm.db2:jcc:11.5.8.0"
com-maxmind-geoip2 = "com.maxmind.geoip2:geoip2:2.16.1"
com-microsoft-sqlserver-mssql-jdbc = "com.microsoft.sqlserver:mssql-jdbc:11.2.3.jre17"
com-oracle-database-jdbc-ojdbc8 = "com.oracle.database.jdbc:ojdbc8:21.7.0.0"
com-zaxxer-HikariCP = "com.zaxxer:HikariCP:5.0.1"
edu-umd-cs-mtc-multithreadedtc = "edu.umd.cs.mtc:multithreadedtc:1.01"
io-lettuce-lettuce-core = "io.lettuce:lettuce-core:6.2.7.RELEASE"
io-projectreactor-reactor-bom = "io.projectreactor:reactor-bom:2022.0.13"
io-projectreactor-reactor-core = { module = "io.projectreactor:reactor-core", version.ref = "io-projectreactor" }
io-projectreactor-reactor-test = { module = "io.projectreactor:reactor-test", version.ref = "io-projectreactor" }
io-spring-javaformat-spring-javaformat-checkstyle = "io.spring.javaformat:spring-javaformat-checkstyle:0.0.40"
io-spring-nohttp-nohttp-checkstyle = "io.spring.nohttp:nohttp-checkstyle:0.0.11"
jakarta-servlet-jakarta-servlet-api = "jakarta.servlet:jakarta.servlet-api:6.0.0"
jakarta-servlet-jsp-jstl-jakarta-servlet-jsp-jstl-api = "jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api:3.0.0"
jakarta-websocket-jakarta-websocket-api = { module = "jakarta.websocket:jakarta.websocket-api", version.ref = "jakarta-websocket" }
jakarta-websocket-jakarta-websocket-client-api = { module = "jakarta.websocket:jakarta.websocket-client-api", version.ref = "jakarta-websocket" }
mysql-mysql-connector-java = "mysql:mysql-connector-java:8.0.33"
nz-net-ultraq-thymeleaf-thymeleaf-layout-dialect = "nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect:3.1.0"
com-squareup-okhttp3-okhttp = "com.squareup.okhttp3:okhttp:3.14.9"
org-apache-derby-derby = { module = "org.apache.derby:derby", version.ref = "org-apache-derby" }
org-apache-derby-derbytools = { module = "org.apache.derby:derbytools", version.ref = "org-apache-derby" }
org-apache-httpcomponents-httpclient = "org.apache.httpcomponents:httpclient:4.5.14"
org-apache-logging-log4j-log4j-core = "org.apache.logging.log4j:log4j-core:2.17.2"
org-aspectj-aspectjweaver = "org.aspectj:aspectjweaver:1.9.20.1"
org-assertj-assertj-core = "org.assertj:assertj-core:3.23.1"
org-codehaus-groovy-groovy-cli-commons = { module = "org.codehaus.groovy:groovy-cli-commons", version.ref = "org-codehaus-groovy" }
org-codehaus-groovy-groovy-json = { module = "org.codehaus.groovy:groovy-json", version.ref = "org-codehaus-groovy" }
org-glassfish-web-jakarta-servlet-jsp-jstl = "org.glassfish.web:jakarta.servlet.jsp.jstl:3.0.1"
org-gretty-gretty-runner-jetty11 = { module = "org.gretty:gretty-runner-jetty11", version.ref = "org-gretty" }
org-gretty-gretty-runner-tomcat10 = { module = "org.gretty:gretty-runner-tomcat10", version.ref = "org-gretty" }
org-gretty-gretty-starter = { module = "org.gretty:gretty-starter", version.ref = "org-gretty" }
org-hamcrest = "org.hamcrest:hamcrest:2.2"
org-hsqldb = "org.hsqldb:hsqldb:2.7.2"
org-junit-junit-bom = "org.junit:junit-bom:5.8.2"
org-junit-jupiter-junit-jupiter-api = "org.junit.jupiter:junit-jupiter-api:5.9.3"
org-junit-jupiter-junit-jupiter-engine = "org.junit.jupiter:junit-jupiter-engine:5.9.3"
org-junit-jupiter-junit-jupiter-params = "org.junit.jupiter:junit-jupiter-params:5.9.3"
org-mariadb-jdbc-mariadb-java-client = "org.mariadb.jdbc:mariadb-java-client:3.0.11"
org-mockito-mockito-bom = "org.mockito:mockito-bom:4.8.1"
org-mongodb-mongodb-driver-core = { module = "org.mongodb:mongodb-driver-core", version.ref = "org-mongodb" }
org-mongodb-mongodb-driver-reactivestreams = { module = "org.mongodb:mongodb-driver-reactivestreams", version.ref = "org-mongodb" }
org-mongodb-mongodb-driver-sync = { module = "org.mongodb:mongodb-driver-sync", version.ref = "org-mongodb" }
org-postgresql = "org.postgresql:postgresql:42.5.4"
org-seleniumhq-selenium-htmlunit-driver = "org.seleniumhq.selenium:htmlunit-driver:4.5.2"
org-seleniumhq-selenium-selenium-support = "org.seleniumhq.selenium:selenium-support:4.5.3"
org-skyscreamer-jsonassert = "org.skyscreamer:jsonassert:1.5.1"
org-slf4j-jcl-over-slf4j = { module = "org.slf4j:jcl-over-slf4j", version.ref = "org-slf4j" }
org-slf4j-log4j-over-slf4j = { module = "org.slf4j:log4j-over-slf4j", version.ref = "org-slf4j" }
org-slf4j-slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "org-slf4j" }
org-springframework-boot-spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools", version.ref = "org-springframework-boot" }
org-springframework-boot-spring-boot-gradle-plugin = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "org-springframework-boot" }
org-springframework-boot-spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator", version.ref = "org-springframework-boot" }
org-springframework-boot-spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "org-springframework-boot" }
org-springframework-boot-spring-boot-starter-data-mongodb = { module = "org.springframework.boot:spring-boot-starter-data-mongodb", version.ref = "org-springframework-boot" }
org-springframework-boot-spring-boot-starter-data-mongodb-reactive = { module = "org.springframework.boot:spring-boot-starter-data-mongodb-reactive", version.ref = "org-springframework-boot" }
org-springframework-boot-spring-boot-starter-data-redis = { module = "org.springframework.boot:spring-boot-starter-data-redis", version.ref = "org-springframework-boot" }
org-springframework-boot-spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security", version.ref = "org-springframework-boot" }
org-springframework-boot-spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "org-springframework-boot" }
org-springframework-boot-spring-boot-starter-thymeleaf = { module = "org.springframework.boot:spring-boot-starter-thymeleaf", version.ref = "org-springframework-boot" }
org-springframework-boot-spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation", version.ref = "org-springframework-boot" }
org-springframework-boot-spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "org-springframework-boot" }
org-springframework-boot-spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux", version.ref = "org-springframework-boot" }
org-springframework-boot-spring-boot-starter-websocket = { module = "org.springframework.boot:spring-boot-starter-websocket", version.ref = "org-springframework-boot" }
org-springframework-data-spring-data-bom = "org.springframework.data:spring-data-bom:2022.0.11"
org-springframework-data-spring-data-mongodb = "org.springframework.data:spring-data-mongodb:4.0.11"
org-springframework-data-spring-data-redis = "org.springframework.data:spring-data-redis:3.0.11"
org-springframework-security-spring-security-bom = "org.springframework.security:spring-security-bom:6.1.5"
org-springframework-spring-framework-bom = "org.springframework:spring-framework-bom:6.0.14"
org-springframework-springloaded = "org.springframework:springloaded:1.2.8.RELEASE"
org-testcontainers-testcontainers-bom = { module = "org.testcontainers:testcontainers-bom", version.ref = "org-testcontainers" }
org-testcontainers-db2 = { module = "org.testcontainers:db2", version.ref = "org-testcontainers" }
org-testcontainers-mariadb = { module = "org.testcontainers:mariadb", version.ref = "org-testcontainers" }
org-testcontainers-mongodb = { module = "org.testcontainers:mongodb", version.ref = "org-testcontainers" }
org-testcontainers-mssqlserver = { module = "org.testcontainers:mssqlserver", version.ref = "org-testcontainers" }
org-testcontainers-mysql = { module = "org.testcontainers:mysql", version.ref = "org-testcontainers" }
org-testcontainers-oracle-xe = { module = "org.testcontainers:oracle-xe", version.ref = "org-testcontainers" }
org-testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "org-testcontainers" }
org-thymeleaf-extras-thymeleaf-extras-springsecurity6 = "org.thymeleaf.extras:thymeleaf-extras-springsecurity6:3.1.2.RELEASE"
org-webjars-bootstrap = "org.webjars:bootstrap:2.3.2"
org-webjars-html5shiv = "org.webjars:html5shiv:3.7.3-1"
org-webjars-knockout = "org.webjars:knockout:3.5.1"
org-webjars-sockjs-client = "org.webjars:sockjs-client:1.5.1"
org-webjars-stomp-websocket = "org.webjars:stomp-websocket:2.3.4"
org-webjars-webjars-locator-core = "org.webjars:webjars-locator-core:0.52"

[plugins]
io-spring-antora-generate-antora-yml = "io.spring.antora.generate-antora-yml:0.0.1"
nl-littlerobots-version-catalog-update = "nl.littlerobots.version-catalog-update:0.8.1"
org-antora = "org.antora:1.0.0"
org-gretty = "org.gretty:4.1.1"
org-springframework-boot = "org.springframework.boot:3.0.12"
org-springframework-boot-aot = "org.springframework.boot.aot:3.0.12"
