[versions]
jakarta-websocket = "2.1.1"
org-apache-derby = "10.16.1.1"
org-mockito = "5.16.1"
org-mongodb = "5.3.1"
org-springframework-boot = "3.5.0-SNAPSHOT"

[libraries]
ch-qos-logback-logback-core = { module = "ch.qos.logback:logback-core", version = "1.5.18" }
com-fasterxml-jackson-core-jackson-databind = "com.fasterxml.jackson.core:jackson-databind:2.18.3"
com-fasterxml-jackson-jackson-bom = "com.fasterxml.jackson:jackson-bom:2.17.3"
com-google-code-findbugs-jsr305 = "com.google.code.findbugs:jsr305:3.0.2" # FIXME: Remove findbugs?
com-h2database-h2 = "com.h2database:h2:2.3.232"
com-hazelcast = "com.hazelcast:hazelcast:5.5.0"
com-ibm-db2-jcc = "com.ibm.db2:jcc:12.1.0.0"
com-microsoft-sqlserver-mssql-jdbc = "com.microsoft.sqlserver:mssql-jdbc:12.8.1.jre11"
com-oracle-database-jdbc-ojdbc8 = "com.oracle.database.jdbc:ojdbc8:23.7.0.25.01"
com-squareup-okhttp3-okhttp = "com.squareup.okhttp3:okhttp:3.14.9"
com-zaxxer-HikariCP = "com.zaxxer:HikariCP:6.2.1"
edu-umd-cs-mtc-multithreadedtc = "edu.umd.cs.mtc:multithreadedtc:1.01" # FIXME: Delete multithreadedtc or update?
io-lettuce-lettuce-core = "io.lettuce:lettuce-core:6.5.5.RELEASE"
io-projectreactor-reactor-bom = "io.projectreactor:reactor-bom:2024.0.4"
jakarta-servlet-jakarta-servlet-api = "jakarta.servlet:jakarta.servlet-api:6.0.0"
jakarta-websocket-jakarta-websocket-api = { module = "jakarta.websocket:jakarta.websocket-api", version.ref = "jakarta-websocket" }
jakarta-websocket-jakarta-websocket-client-api = { module = "jakarta.websocket:jakarta.websocket-client-api", version.ref = "jakarta-websocket" }
mysql-mysql-connector-java = "com.mysql:mysql-connector-j:9.1.0"
org-apache-derby-derby = { module = "org.apache.derby:derby", version.ref = "org-apache-derby" }
org-apache-derby-derbytools = { module = "org.apache.derby:derbytools", version.ref = "org-apache-derby" }
org-aspectj-aspectjweaver = "org.aspectj:aspectjweaver:1.9.23"
org-assertj-assertj-core = "org.assertj:assertj-core:3.27.3"
org-awaitility-awaitility = "org.awaitility:awaitility:4.3.0"
org-hamcrest = "org.hamcrest:hamcrest:3.0"
org-hsqldb = "org.hsqldb:hsqldb:2.7.3" # hsqldb 2.7.4 breaks Spring Data https://sourceforge.net/p/hsqldb/bugs/1725/
org-junit-junit-bom = "org.junit:junit-bom:5.12.1"
org-mariadb-jdbc-mariadb-java-client = "org.mariadb.jdbc:mariadb-java-client:3.5.2"
org-mockito-mockito-bom = { module = "org.mockito:mockito-bom", version.ref = "org-mockito" }
org-mongodb-mongodb-driver-core = { module = "org.mongodb:mongodb-driver-core", version.ref = "org-mongodb" }
org-mongodb-mongodb-driver-reactivestreams = { module = "org.mongodb:mongodb-driver-reactivestreams", version.ref = "org-mongodb" }
org-mongodb-mongodb-driver-sync = { module = "org.mongodb:mongodb-driver-sync", version.ref = "org-mongodb" }
org-postgresql = "org.postgresql:postgresql:42.7.5"
org-springframework-data-spring-data-bom = "org.springframework.data:spring-data-bom:2025.0.0-M2"
org-springframework-security-spring-security-bom = "org.springframework.security:spring-security-bom:6.5.0-M3"
org-springframework-spring-framework-bom = "org.springframework:spring-framework-bom:6.2.5"
org-testcontainers-testcontainers-bom = { module = "org.testcontainers:testcontainers-bom", version = "1.20.6" }
io-spring-security-release-plugin = "io.spring.gradle:spring-security-release-plugin:1.0.3"
org-springframework-boot-spring-boot-gradle-plugin = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "org-springframework-boot" }
io-spring-javaformat-spring-javaformat-checkstyle = "io.spring.javaformat:spring-javaformat-checkstyle:0.0.43"
io-spring-nohttp-nohttp-checkstyle = "io.spring.nohttp:nohttp-checkstyle:0.0.11"